#!/usr/bin/env python3
"""Editable export of the A6 card deck — called by make_cards.py --editable.

Writes to material/source/cards/:
    front_<n>.png       front backgrounds (glow + scanlines + noise bars),
                        one per card, language-independent, 300 dpi
    icon_<n>.png        the emoji icon, transparent
    README.md           what to open where

(A PowerPoint deck used to be generated here too; it was dropped — the
HTML deck prints better and the PNG layers cover image-editor workflows.)

Needs pillow (in dev/requirements-tools.txt).
"""

from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
OUT = ROOT / "material" / "source" / "cards"

MM_PER_IN = 25.4
DPI = 300                      # raster resolution for the background layers


def mm2px(mm):
    return int(round(mm / MM_PER_IN * DPI))


def hex2rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def render_front_bg(color, L, path):
    """Dark card background: vertical gradient, two accent glows, scanlines,
    noise bars, accent top bar — the parts a PowerPoint shape cannot do."""
    from PIL import Image, ImageDraw, ImageFilter

    W, H = mm2px(L["w"]), mm2px(L["h"])
    accent = hex2rgb(color)
    bg, bg2 = (13, 17, 23), (22, 27, 39)

    im = Image.new("RGB", (W, H), bg)
    d = ImageDraw.Draw(im)
    for y in range(H):
        f = y / H
        d.line([(0, y), (W, y)],
               fill=tuple(int(bg[i] + (bg2[i] - bg[i]) * (1 - f)) for i in range(3)))

    def glow(cx, cy, rx, ry, alpha):
        layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        ImageDraw.Draw(layer).ellipse([cx - rx, cy - ry, cx + rx, cy + ry],
                                      fill=accent + (alpha,))
        layer = layer.filter(ImageFilter.GaussianBlur(rx / 2))
        im.paste(Image.alpha_composite(im.convert("RGBA"), layer).convert("RGB"))

    glow(W * 0.78, H * 0.12, mm2px(42), mm2px(28), 108)
    glow(W * 0.12, H * 0.92, mm2px(38), mm2px(28), 66)

    d = ImageDraw.Draw(im, "RGBA")
    # noise bars (same positions as the HTML deck)
    bars = [(0.20, 0.00, 0.36, 1.1, accent, 128),
            (0.33, 0.76, 0.24, 0.7, (41, 231, 255), 115),
            (0.70, 0.07, 0.28, 1.5, (255, 46, 138), 97),
            (0.82, 0.80, 0.16, 1.1, accent, 128)]
    for ty, tx, tw, th, rgb, a in bars:
        x0 = int(W * tx)
        d.rectangle([x0, int(H * ty), x0 + int(W * tw),
                     int(H * ty) + mm2px(th)], fill=rgb + (a,))
    # scanlines
    step = mm2px(0.95)
    for y in range(0, H, max(2, step)):
        d.rectangle([0, y, W, y + max(1, mm2px(0.3))], fill=(255, 255, 255, 14))
    # accent top bar
    d.rectangle([0, 0, W, mm2px(L["bar"])], fill=accent + (255,))

    im.save(path, optimize=True)


def render_icon(char, size_mm, path):
    from PIL import Image, ImageDraw, ImageFont
    f = ImageFont.truetype("/System/Library/Fonts/Apple Color Emoji.ttc", 160)
    tmp = Image.new("RGBA", (220, 220), (0, 0, 0, 0))
    ImageDraw.Draw(tmp).text((10, 10), char, font=f, embedded_color=True)
    box = tmp.getbbox()
    tmp = tmp.crop(box) if box else tmp
    side = mm2px(size_mm)
    ratio = side / max(tmp.size)
    tmp = tmp.resize((max(1, int(tmp.width * ratio)),
                      max(1, int(tmp.height * ratio))), Image.LANCZOS)
    tmp.save(path, optimize=True)


def run(langs=("de", "en")):
    import make_cards as mc

    OUT.mkdir(parents=True, exist_ok=True)
    L = mc.L

    # one background + icon per card (language-independent)
    cards_meta = []
    for i in range(6):
        cards_meta.append(dict(color=mc.ACCENT_STATION[i],
                               icon=mc.ICONS_STATION[i]))
    for i in range(6):
        cards_meta.append(dict(color=mc.ACCENT_DISCUSS[i],
                               icon=mc.ICONS_DISCUSS[i]))
    for n, m in enumerate(cards_meta, 1):
        bg = OUT / f"front_{n:02d}.png"
        ic = OUT / f"icon_{n:02d}.png"
        if not bg.exists():
            render_front_bg(m["color"], L, bg)
        if not ic.exists():
            render_icon(m["icon"], L["icon"] - 3, ic)
    print(f"  ✓ {len(cards_meta)} Hintergründe + Icons (300 dpi)")

    (OUT / "README.md").write_text(READ_ME, encoding="utf-8")
    print(f"→ {OUT.relative_to(ROOT)}")


READ_ME = """# Editable A6 card deck — raw layers

Generated by `bash setup/tools.sh cards --editable`. Re-running overwrites
these files — save your own edits under a new name.

| File | What it is |
|---|---|
| `front_NN.png` | front background per card, 300 dpi — carries the glitch look (glow, scanlines, colour bars, accent bar) |
| `icon_NN.png` | the emoji icon, transparent |

Card order: stations 1–6, then discussion cards 1–6. The accent colours
are `ACCENT_STATION` / `ACCENT_DISCUSS` in `setup/make_cards.py`.

## Photoshop / Illustrator / Affinity

Use `front_NN.png` as the background layer and set your own type on top
(Helvetica Neue, Bold for the title). Brand colours `#400b67` / `#c32683`.

## Print-ready / vector

Open `material/cards/cards_de.html` (or `_en`) in a browser and print to PDF — the
PDF keeps the text as editable vector type. Double-sided: flip on the
**short** edge.
"""


if __name__ == "__main__":
    run()
